"""Update student number constraints

Revision ID: 7e38adb611d3
Revises: 2ad1bd2f4357
Create Date: 2026-08-11 21:10:16.406828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e38adb611d3'
down_revision: Union[str, Sequence[str], None] = '2ad1bd2f4357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_student_admission_school_session'), 'students', type_='unique')
    op.create_unique_constraint('uq_student_admission_school', 'students', ['school_id', 'admission_no'])
    op.create_unique_constraint('uq_student_roll_school_session_class', 'students', ['school_id', 'session_id', 'class_id', 'roll_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_roll_school_session_class', 'students', type_='unique')
    op.drop_constraint('uq_student_admission_school', 'students', type_='unique')
    op.create_unique_constraint(op.f('uq_student_admission_school_session'), 'students', ['school_id', 'session_id', 'admission_no'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
